name: Java Tests

on:
  pull_request:

jobs:
  build:
    uses: yandex-practicum/java-kanban/.github/workflows/api-test.yml@ci

    steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Specify the distribution here
        java-version: 21

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        find ./src/test/java -type f -name "*.java" > tests.txt
        javac -d out -cp ./out:./tests/lib/junit-platform-console-standalone-1.9.3.jar:./tests/lib/gson-2.10.1.jar @tests.txt

    - name: Run tests
      run: |
        java -cp ./out:./tests/lib/junit-platform-console-standalone-1.9.3.jar org.junit.platform.console.ConsoleLauncher --scan-classpath
